GCon/Controllers/ContactController.cs
using System.Linq;
using System.Web.Mvc;
using GCon.Models;
using GCon.ViewModels;
using System.Data.Entity;

namespace GCon.Controllers
{
    public class ContactController : Controller
    {

        private ApplicationDbContext _context;

        public ContactController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Contacts/ContactList/id
        public ActionResult ContactList(int id)
        {
            var viewModel = new ContactListViewModel
            {
                Id = id,
                Contacts = _context.Contacts.Where(c => c.AddressGroupId == id),
                AddressGroupName = _context.AddressGroups.SingleOrDefault(add => add.Id == id).Name
            };

            return View(viewModel);
        }

        public ActionResult NewContact(int id)
        {
            var viewModel = new NewContactViewModel
            {
                Id = id,
                Contact = new Contact(),
                AddressGroupName = _context.AddressGroups.SingleOrDefault(add => add.Id == id).Name
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveContact(int id,Contact contact)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new NewContactViewModel
                {
                    Id = id,
                    Contact = contact
                };

                return View("NewContact", viewModel);
            }
            if (contact.Id == 0)
            {
                contact.AddressGroupId = id;
                _context.Contacts.Add(contact);
            }
            else
            {
                var contactInDb = _context.Contacts.SingleOrDefault(c => c.Id == contact.Id);

                contactInDb.Name = contact.Name;
                contactInDb.Email = contact.Email;
                contactInDb.PhoneNumber = contact.PhoneNumber;
                contactInDb.Address = contact.Address;
            }

            _context.SaveChanges();
            return RedirectToAction("ContactList",new {id = id});
        }

        public ActionResult Edit(int id)
        {
            var contactInDb = _context.Contacts.Include(c => c.AddressGroup).SingleOrDefault(c => c.Id == id);
            var viewModel = new NewContactViewModel
            {
                Id = contactInDb.AddressGroupId,
                Contact = contactInDb,
                AddressGroupName = contactInDb.AddressGroup.Name
            };

            return View("NewContact", viewModel);
        }
    }
}

GCon/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GCon.Models;
using GCon.ViewModels;
using System.Data.Entity;

namespace GCon.Controllers
{
    public class GroupController : Controller
    {

        private ApplicationDbContext _context;

        public GroupController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Group
        public ActionResult Index()
        {
            var addressGroups = _context.AddressGroups.Include(add => add.AddressGroupType).ToList();

            return View(addressGroups);
        }


        // GET: Group/NewGroup
        public ActionResult NewGroup()
        {
            var viewModel = new AddressGroupViewModel
            {
                AddressGroupTypes = _context.AddressGroupTypes.ToList(),
                AddressGroup = new AddressGroup()
            };

            return View(viewModel);
        }



        // GET: Group/Save/AddressGroup
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(AddressGroup addressGroup)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new AddressGroupViewModel
                {
                    AddressGroupTypes = _context.AddressGroupTypes.ToList(),
                    AddressGroup = addressGroup
                };

                return View("NewGroup", viewModel);
            }
            if (addressGroup.Id == 0)
            {

                addressGroup.AddedDay = DateTime.Now;

                _context.AddressGroups.Add(addressGroup);
            }
            else
            {
                var addressGroupInDb = _context.AddressGroups.SingleOrDefault(add => add.Id == addressGroup.Id);

                addressGroupInDb.Name = addressGroup.Name;
                addressGroupInDb.AddressGroupTypeId = addressGroup.AddressGroupTypeId;

            }

            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Group/Edit/id
        public ActionResult Edit(int id)
        {
            var viewModel = new AddressGroupViewModel
            {
                AddressGroup = _context.AddressGroups.SingleOrDefault(add => add.Id == id),
                AddressGroupTypes = _context.AddressGroupTypes.ToList()
            };

            return View("NewGroup", viewModel);
        }
    }
}

GCon/Views/Group/Index.cshtml
@using GCon.Models
@model IEnumerable<AddressGroup>
           

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Address Book</h2>

@Html.ActionLink("New Book","NewGroup",null,new {@class="btn btn-primary"})
<br/> <br/>
<table class="table table-bordered table-hover" id="group" style="text-align: center">
    <thead>
        <tr >
            <th style="text-align: center">Book Name</th>
            <th style="text-align: center">Book Type</th>
            <th style="text-align: center">Action</th>

        </tr>
    </thead>
    
    @foreach (AddressGroup addressGroup in Model)
    {
        <tr>
            <td>@Html.ActionLink(addressGroup.Name,"ContactList","Contact",new {id = addressGroup.Id},null)</td>
            <td>@addressGroup.AddressGroupType.Name</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = addressGroup.Id }, new { @class = "btn btn-link" }) | <button class="btn btn-link js-delete" data-add-id="@addressGroup.Id">Delete</button>
            </td>
        </tr>
    }

</table>

@section scripts
{
    <script>
        $(document).ready(function() {

            var table = $("#group").DataTable();

            $("#group").on("click", ".js-delete", function() {

                var button = $(this);
                
                bootbox.confirm("Are You Sure To Delete This", function (result) {

                    if (result) {

                        $.ajax({

                            url: "/api/AddressGroups/" + button.attr("data-add-id"),
                            method: "DELETE",
                            success: function() {

                                table.row(button.parents("tr")).remove().draw();
                            }
                        });
                    }
                });
            });

        });
    </script>
}

GCon/Views/Group/NewGroup.cshtml
@model GCon.ViewModels.AddressGroupViewModel

@{
    ViewBag.Title = "NewGroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Group</h2>

@using (Html.BeginForm("Save","Group"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.AddressGroup.Name)
        @Html.TextBoxFor(m => m.AddressGroup.Name,new { @class = "form-control"})
        @Html.ValidationMessageFor(m => m.AddressGroup.Name)
    </div>
    
    <div class="form-group">
        @Html.LabelFor(m => m.AddressGroup.AddressGroupTypeId)
        @Html.DropDownListFor(m => m.AddressGroup.AddressGroupTypeId,new SelectList(Model.AddressGroupTypes,"Id","Name"),"Select a Type",new { @class="form-control"})
        @Html.ValidationMessageFor(m => m.AddressGroup.AddressGroupTypeId)
    </div>
    
    @Html.HiddenFor(m => m.AddressGroup.Id)
    @Html.AntiForgeryToken()
    <input type="submit" value="Save" class="btn btn-primary"/>
}

@section scripts
{
    @Scripts.Render("~/bundels/jqueryval")
}